# theme: jekyll-theme-minimal
remote_theme: "jekyll/minima@1e8a445"
title: Igor Tominec
logo: /igor.jpg
#description: [A short description of your site's purpose]

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Navigation bar links
header_pages:
  - index.md
  - research.md
  - collaboration.md
  - teaching.md
  - CV.md
